// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedbackService/pb/feedback.proto

package feedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassengerId struct {
	PassengerId          int32    `protobuf:"varint,1,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerId) Reset()         { *m = PassengerId{} }
func (m *PassengerId) String() string { return proto.CompactTextString(m) }
func (*PassengerId) ProtoMessage()    {}
func (*PassengerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{0}
}

func (m *PassengerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerId.Unmarshal(m, b)
}
func (m *PassengerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerId.Marshal(b, m, deterministic)
}
func (m *PassengerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerId.Merge(m, src)
}
func (m *PassengerId) XXX_Size() int {
	return xxx_messageInfo_PassengerId.Size(m)
}
func (m *PassengerId) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerId.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerId proto.InternalMessageInfo

func (m *PassengerId) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

type BookingCode struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingCode) Reset()         { *m = BookingCode{} }
func (m *BookingCode) String() string { return proto.CompactTextString(m) }
func (*BookingCode) ProtoMessage()    {}
func (*BookingCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{1}
}

func (m *BookingCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingCode.Unmarshal(m, b)
}
func (m *BookingCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingCode.Marshal(b, m, deterministic)
}
func (m *BookingCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingCode.Merge(m, src)
}
func (m *BookingCode) XXX_Size() int {
	return xxx_messageInfo_BookingCode.Size(m)
}
func (m *BookingCode) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingCode.DiscardUnknown(m)
}

var xxx_messageInfo_BookingCode proto.InternalMessageInfo

func (m *BookingCode) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type Feedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerId          int32    `protobuf:"varint,2,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()         { *m = Feedback{} }
func (m *Feedback) String() string { return proto.CompactTextString(m) }
func (*Feedback) ProtoMessage()    {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{2}
}

func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feedback.Unmarshal(m, b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
}
func (m *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(m, src)
}
func (m *Feedback) XXX_Size() int {
	return xxx_messageInfo_Feedback.Size(m)
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *Feedback) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *Feedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type ListOfFeedback struct {
	ListOfFeedback       []*Feedback `protobuf:"bytes,1,rep,name=listOfFeedback,proto3" json:"listOfFeedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListOfFeedback) Reset()         { *m = ListOfFeedback{} }
func (m *ListOfFeedback) String() string { return proto.CompactTextString(m) }
func (*ListOfFeedback) ProtoMessage()    {}
func (*ListOfFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{3}
}

func (m *ListOfFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfFeedback.Unmarshal(m, b)
}
func (m *ListOfFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfFeedback.Marshal(b, m, deterministic)
}
func (m *ListOfFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfFeedback.Merge(m, src)
}
func (m *ListOfFeedback) XXX_Size() int {
	return xxx_messageInfo_ListOfFeedback.Size(m)
}
func (m *ListOfFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfFeedback proto.InternalMessageInfo

func (m *ListOfFeedback) GetListOfFeedback() []*Feedback {
	if m != nil {
		return m.ListOfFeedback
	}
	return nil
}

type AddFbkResponse struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerId          int32    `protobuf:"varint,2,opt,name=passengerId,proto3" json:"passengerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFbkResponse) Reset()         { *m = AddFbkResponse{} }
func (m *AddFbkResponse) String() string { return proto.CompactTextString(m) }
func (*AddFbkResponse) ProtoMessage()    {}
func (*AddFbkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{4}
}

func (m *AddFbkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFbkResponse.Unmarshal(m, b)
}
func (m *AddFbkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFbkResponse.Marshal(b, m, deterministic)
}
func (m *AddFbkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFbkResponse.Merge(m, src)
}
func (m *AddFbkResponse) XXX_Size() int {
	return xxx_messageInfo_AddFbkResponse.Size(m)
}
func (m *AddFbkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFbkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFbkResponse proto.InternalMessageInfo

func (m *AddFbkResponse) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *AddFbkResponse) GetPassengerId() int32 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

type DeleteByPasIdResponse struct {
	NumberOfFbDeleted    int32    `protobuf:"varint,1,opt,name=numberOfFbDeleted,proto3" json:"numberOfFbDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByPasIdResponse) Reset()         { *m = DeleteByPasIdResponse{} }
func (m *DeleteByPasIdResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByPasIdResponse) ProtoMessage()    {}
func (*DeleteByPasIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1c1d6288c4e6004, []int{5}
}

func (m *DeleteByPasIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByPasIdResponse.Unmarshal(m, b)
}
func (m *DeleteByPasIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByPasIdResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByPasIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByPasIdResponse.Merge(m, src)
}
func (m *DeleteByPasIdResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByPasIdResponse.Size(m)
}
func (m *DeleteByPasIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByPasIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByPasIdResponse proto.InternalMessageInfo

func (m *DeleteByPasIdResponse) GetNumberOfFbDeleted() int32 {
	if m != nil {
		return m.NumberOfFbDeleted
	}
	return 0
}

func init() {
	proto.RegisterType((*PassengerId)(nil), "feedback.PassengerId")
	proto.RegisterType((*BookingCode)(nil), "feedback.BookingCode")
	proto.RegisterType((*Feedback)(nil), "feedback.Feedback")
	proto.RegisterType((*ListOfFeedback)(nil), "feedback.ListOfFeedback")
	proto.RegisterType((*AddFbkResponse)(nil), "feedback.AddFbkResponse")
	proto.RegisterType((*DeleteByPasIdResponse)(nil), "feedback.DeleteByPasIdResponse")
}

func init() { proto.RegisterFile("feedbackService/pb/feedback.proto", fileDescriptor_f1c1d6288c4e6004) }

var fileDescriptor_f1c1d6288c4e6004 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x69, 0x4b, 0x5f, 0xfa, 0x4e, 0x34, 0xd0, 0x85, 0x42, 0xc8, 0xc5, 0x98, 0x53, 0x0f,
	0xd2, 0x40, 0xc5, 0x8b, 0x97, 0x62, 0xd5, 0x94, 0x42, 0xa1, 0x25, 0xfa, 0x05, 0xb2, 0xdd, 0x49,
	0x89, 0xa9, 0xd9, 0x90, 0x8d, 0x82, 0x1f, 0xc4, 0xef, 0x2b, 0x8d, 0xc9, 0xee, 0x36, 0x8d, 0x78,
	0xf1, 0x38, 0xcf, 0xce, 0x3c, 0xfb, 0x9b, 0x3f, 0x70, 0x19, 0x21, 0x32, 0x1a, 0x6e, 0x93, 0x27,
	0xcc, 0xdf, 0xe3, 0x2d, 0x7a, 0x19, 0xf5, 0x6a, 0x69, 0x92, 0xe5, 0xbc, 0xe0, 0x64, 0x50, 0xc7,
	0xae, 0x07, 0xc6, 0x26, 0x14, 0x02, 0xd3, 0x1d, 0xe6, 0x4b, 0x46, 0x1c, 0x30, 0x32, 0x15, 0x5a,
	0x1d, 0xa7, 0x33, 0xee, 0x07, 0xba, 0x74, 0x28, 0x98, 0x73, 0x9e, 0xc4, 0xe9, 0xee, 0x9e, 0x33,
	0x3c, 0x14, 0x50, 0x15, 0x96, 0x05, 0xff, 0x03, 0x5d, 0x72, 0x5f, 0x60, 0xe0, 0x57, 0xbf, 0xfd,
	0x9e, 0xdd, 0x04, 0xe8, 0x9e, 0x00, 0x10, 0x1b, 0x24, 0xbd, 0xd5, 0x2b, 0x0d, 0x54, 0x37, 0x2b,
	0x30, 0x57, 0xb1, 0x28, 0xd6, 0x91, 0xfc, 0xf1, 0x16, 0xcc, 0xfd, 0x91, 0x62, 0x75, 0x9c, 0xde,
	0xd8, 0x98, 0x92, 0x89, 0x1c, 0x49, 0xfd, 0x12, 0x34, 0x32, 0xdd, 0x67, 0x30, 0xef, 0x18, 0xf3,
	0x69, 0x12, 0xa0, 0xc8, 0x78, 0x2a, 0xf0, 0x2f, 0xf8, 0xdd, 0x47, 0x18, 0x3d, 0xe0, 0x1e, 0x0b,
	0x9c, 0x7f, 0x6c, 0x42, 0xb1, 0x64, 0xd2, 0xfc, 0x0a, 0x86, 0xe9, 0xdb, 0x2b, 0xc5, 0x7c, 0x1d,
	0xf9, 0xf4, 0x3b, 0xa5, 0xde, 0xc0, 0xe9, 0xc3, 0xf4, 0xb3, 0x0b, 0x43, 0xb9, 0x39, 0xd9, 0xee,
	0x0d, 0xf4, 0x4b, 0x64, 0xd2, 0xd2, 0x9f, 0x6d, 0x29, 0xad, 0xd1, 0xd7, 0x0c, 0xce, 0x16, 0x58,
	0xf8, 0xb4, 0x42, 0x22, 0x23, 0x95, 0xa9, 0x5d, 0x87, 0x6e, 0xd0, 0x18, 0xf3, 0x0c, 0x48, 0x65,
	0xa0, 0x1f, 0x87, 0x66, 0xa3, 0xc9, 0x76, 0x0b, 0x1b, 0x59, 0xc0, 0xf9, 0xd1, 0x54, 0x7e, 0x42,
	0xb8, 0x50, 0x72, 0xeb, 0x14, 0xe9, 0xbf, 0xf2, 0xc2, 0xaf, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x00, 0x2c, 0x27, 0x42, 0x06, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PassengerFeedbackClient is the client API for PassengerFeedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerFeedbackClient interface {
	AddFb(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AddFbkResponse, error)
	GetFbByPasId(ctx context.Context, in *PassengerId, opts ...grpc.CallOption) (*ListOfFeedback, error)
	GetFbByBookingCode(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*Feedback, error)
	DeleteByPasId(ctx context.Context, in *PassengerId, opts ...grpc.CallOption) (*DeleteByPasIdResponse, error)
}

type passengerFeedbackClient struct {
	cc *grpc.ClientConn
}

func NewPassengerFeedbackClient(cc *grpc.ClientConn) PassengerFeedbackClient {
	return &passengerFeedbackClient{cc}
}

func (c *passengerFeedbackClient) AddFb(ctx context.Context, in *Feedback, opts ...grpc.CallOption) (*AddFbkResponse, error) {
	out := new(AddFbkResponse)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/AddFb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) GetFbByPasId(ctx context.Context, in *PassengerId, opts ...grpc.CallOption) (*ListOfFeedback, error) {
	out := new(ListOfFeedback)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/GetFbByPasId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) GetFbByBookingCode(ctx context.Context, in *BookingCode, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/GetFbByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerFeedbackClient) DeleteByPasId(ctx context.Context, in *PassengerId, opts ...grpc.CallOption) (*DeleteByPasIdResponse, error) {
	out := new(DeleteByPasIdResponse)
	err := c.cc.Invoke(ctx, "/feedback.PassengerFeedback/DeleteByPasId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerFeedbackServer is the server API for PassengerFeedback service.
type PassengerFeedbackServer interface {
	AddFb(context.Context, *Feedback) (*AddFbkResponse, error)
	GetFbByPasId(context.Context, *PassengerId) (*ListOfFeedback, error)
	GetFbByBookingCode(context.Context, *BookingCode) (*Feedback, error)
	DeleteByPasId(context.Context, *PassengerId) (*DeleteByPasIdResponse, error)
}

// UnimplementedPassengerFeedbackServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerFeedbackServer struct {
}

func (*UnimplementedPassengerFeedbackServer) AddFb(ctx context.Context, req *Feedback) (*AddFbkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFb not implemented")
}
func (*UnimplementedPassengerFeedbackServer) GetFbByPasId(ctx context.Context, req *PassengerId) (*ListOfFeedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFbByPasId not implemented")
}
func (*UnimplementedPassengerFeedbackServer) GetFbByBookingCode(ctx context.Context, req *BookingCode) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFbByBookingCode not implemented")
}
func (*UnimplementedPassengerFeedbackServer) DeleteByPasId(ctx context.Context, req *PassengerId) (*DeleteByPasIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPasId not implemented")
}

func RegisterPassengerFeedbackServer(s *grpc.Server, srv PassengerFeedbackServer) {
	s.RegisterService(&_PassengerFeedback_serviceDesc, srv)
}

func _PassengerFeedback_AddFb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Feedback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).AddFb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/AddFb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).AddFb(ctx, req.(*Feedback))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_GetFbByPasId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).GetFbByPasId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/GetFbByPasId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).GetFbByPasId(ctx, req.(*PassengerId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_GetFbByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingCode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).GetFbByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/GetFbByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).GetFbByBookingCode(ctx, req.(*BookingCode))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerFeedback_DeleteByPasId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerFeedbackServer).DeleteByPasId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.PassengerFeedback/DeleteByPasId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerFeedbackServer).DeleteByPasId(ctx, req.(*PassengerId))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerFeedback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedback.PassengerFeedback",
	HandlerType: (*PassengerFeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFb",
			Handler:    _PassengerFeedback_AddFb_Handler,
		},
		{
			MethodName: "GetFbByPasId",
			Handler:    _PassengerFeedback_GetFbByPasId_Handler,
		},
		{
			MethodName: "GetFbByBookingCode",
			Handler:    _PassengerFeedback_GetFbByBookingCode_Handler,
		},
		{
			MethodName: "DeleteByPasId",
			Handler:    _PassengerFeedback_DeleteByPasId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedbackService/pb/feedback.proto",
}
